import _apolloServer from 'apollo-server';
const { ApolloServer, gql } = _apolloServer;
import { ApolloServer2, gql2 } from 'pollo-serve';
import _my$softW4re from 'my$soft-w4re';
const { ApolloServer3, gql3 } = _my$softW4re;
import _someOtherServer from 'some-other-server';
const { ApolloServer4, gql4 } = _someOtherServer;
void ApolloServer;
void ApolloServer2;
void ApolloServer3;
void ApolloServer4;
void gql;
void gql2;
void gql3;
void gql4;
